export type TransactionType =
  | 'income'             // আয়
  | 'expense'            // ব্যয়
  | 'transfer'           // এক অ্যাকাউন্ট থেকে অন্যটিতে স্থানান্তর
  | 'deposit'            // জমা
  | 'withdrawal'         // উত্তোলন
  | 'money_given'        // ধার/টাকা দেওয়া (Receivable)
  | 'money_received'     // ধার ফেরত পাওয়া (Receivable reduction)
  | 'debt_payment'       // দেনা পরিশোধ (Payable reduction)
  | 'receivable'         // পাওনা
  | 'payable'            // দেনা
  | 'credit_purchase'    // ক্রেডিট কার্ডে কেনাকাটা
  | 'credit_payment'     // ক্রেডিট কার্ড বিল পরিশোধ
  | 'refund'             // রিফান্ড/টাকা ফেরত
  | 'adjustment';        // ব্যালেন্স সমন্বয়

export type AccountType =
  | 'cash'
  | 'bank'
  | 'bkash'
  | 'nagad'
  | 'rocket'
  | 'upay'
  | 'debit_card'
  | 'credit_card'
  | 'custom';

export interface Account {
  id: string;
  name: string;
  nameBn: string;
  type: AccountType;
  accountNumber?: string;
  bankName?: string;
  initialBalance?: number; // Opening base balance
  balance: number; // For credit card, this represents negative balance or outstanding
  creditLimit?: number;
  availableCredit?: number;
  color: string;
  iconName: string;
  isDefault?: boolean;
  isArchived?: boolean;
  createdAt: number;
  updatedAt: number;
}

export interface Category {
  id: string;
  name: string;
  nameBn: string;
  type: 'income' | 'expense' | 'both';
  icon: string;
  color: string;
  subcategories: string[];
  isCustom?: boolean;
}

export interface Person {
  id: string;
  name: string;
  phone?: string;
  phoneNumber?: string;
  relationship?: string;
  email?: string;
  totalGiven: number;    // কত টাকা দিয়েছি (মোট ধার)
  totalReceived: number; // কত ফেরত পেয়েছি
  currentReceivable: number; // এখনও কত পাবো
  totalBorrowed: number; // আমি কত ধার নিয়েছি (Payable)
  totalRepaid: number;   // আমি কত শোধ করেছি
  currentPayable: number;    // আমি এখনও কত দেবো
  notes?: string;
  createdAt: number;
  updatedAt: number;
}

export interface TransactionEditLog {
  timestamp: number;
  changedFields: string[];
  previousValues: Record<string, any>;
  reason?: string;
}

export interface Transaction {
  id: string;
  amount: number;
  type: TransactionType;
  categoryId?: string;
  subcategory?: string;
  accountId: string;          // Source account
  toAccountId?: string;        // Destination account for transfers
  personId?: string;           // Person involved in receivable/payable/loan
  paymentMethod?: string;
  date: string;                // YYYY-MM-DD
  time: string;                // HH:mm
  timestamp: number;
  description: string;
  notes?: string;
  status: 'completed' | 'pending' | 'cleared';
  isRecurring?: boolean;
  recurringId?: string;
  reminderId?: string;
  tags?: string[];
  confidenceScore?: number;    // 0 to 1
  rawPrompt?: string;          // Original AI prompt if generated by voice/text
  editHistory?: TransactionEditLog[];
  syncStatus?: 'synced' | 'pending' | 'conflict';
  createdAt: number;
  updatedAt: number;
}

export interface Budget {
  id: string;
  categoryId: string;
  month: string; // YYYY-MM
  allocatedAmount: number;
  monthlyLimit?: number;
  warningThresholds: number[]; // e.g. [70, 85, 100]
  createdAt: number;
  updatedAt: number;
}

export interface RecurringExpense {
  id: string;
  title: string;
  amount: number;
  dueDay?: number;
  frequency: 'daily' | 'weekly' | 'monthly' | 'yearly' | 'custom';
  categoryId: string;
  accountId?: string;
  type?: TransactionType;
  customIntervalDays?: number;
  nextDueDate?: string; // YYYY-MM-DD
  autoRecord?: boolean; // Automatically add transaction or require approval
  lastRunDate?: string;
  isActive: boolean;
  createdAt: number;
}

export interface Reminder {
  id: string;
  title: string;
  amount: number;
  dueDate: string; // YYYY-MM-DD
  categoryId?: string;
  accountId?: string;
  personId?: string;
  status: 'pending' | 'paid' | 'dismissed';
  autoMatchKeywords?: string[];
  relatedTransactionId?: string;
  paidAt?: number;
  createdAt?: number;
}

export interface ParsedItemDraft {
  tempId: string;
  amount: number;
  type: TransactionType;
  categoryName: string;
  categoryId?: string;
  subcategory?: string;
  accountName: string;
  accountId?: string;
  toAccountName?: string;
  toAccountId?: string;
  personName?: string;
  personId?: string;
  date: string;
  description: string;
  notes?: string;
  confidenceScore: number;
  reasoningBn: string;
  isHighConfidence: boolean;
  matchedReminderId?: string;
}

export interface AIParseResponse {
  summaryBn: string;
  items: ParsedItemDraft[];
  totalIncome: number;
  totalExpense: number;
  netImpact: number;
  ambiguityNotes?: string;
  suggestedQuestions?: string[];
}

export interface FinancialHealthMetrics {
  todayIncome: number;
  todayExpense: number;
  todayNet: number;
  monthIncome: number;
  monthExpense: number;
  monthSavings: number;
  savingsRate: number; // percentage
  totalCash: number;
  totalBank: number;
  totalMobileWallet: number;
  totalCreditOutstanding: number;
  totalReceivable: number;
  totalPayable: number;
  netWorth: number;
}

export interface MonthlyCategoryStats {
  categoryId: string;
  categoryName: string;
  categoryNameBn: string;
  color: string;
  icon: string;
  amount: number;
  percentage: number;
  budgetAllocated?: number;
  budgetUsedPercentage?: number;
  transactionCount: number;
}

export interface MonthlyAccountStats {
  accountId: string;
  accountName: string;
  accountType: AccountType;
  inflow: number;
  outflow: number;
  netFlow: number;
  currentBalance: number;
}

export type Language = 'bn' | 'en';
export type ThemeMode = 'dark' | 'light' | 'system';

export interface SecuritySettings {
  isPinEnabled: boolean;
  pinHash?: string; // 4-6 digit hashed PIN
  isBiometricEnabled: boolean;
  autoLockMinutes: number;
  lastUnlockedTime?: number;
  dataEncryptionEnabled: boolean;
}

export interface UserSettings {
  language: Language;
  theme: ThemeMode;
  isPinProtected: boolean;
  pinHash?: string;
  autoAddHighConfidence: boolean;
  deviceId: string;
  lastSyncedAt?: string;
}

export interface AppSettings {
  language: Language;
  theme: ThemeMode;
  currency: 'BDT' | 'USD' | 'EUR';
  currencySymbol: string;
  autoAddHighConfidence: boolean;
  soundEnabled: boolean;
  hapticsEnabled: boolean;
  isPinProtected?: boolean;
  pinHash?: string;
  deviceId?: string;
  lastSyncedAt?: string;
  security: SecuritySettings;
  cloudSync: {
    enabled: boolean;
    autoSyncIntervalMinutes: number;
    lastSyncedAt?: number;
    syncState: 'idle' | 'syncing' | 'synced' | 'error';
    deviceId: string;
    cloudEmail?: string;
  };
}

export type PromotionTheme =
  | 'royal_gold'
  | 'emerald_green'
  | 'royal_blue'
  | 'deep_purple'
  | 'ruby_red'
  | 'midnight_dark'
  | 'cyber_neon';

export interface PromotionConfig {
  id: string;
  enabled: boolean;
  websiteName: string;
  badgeTag: string;
  websiteUrl: string;
  title: string;
  description: string;
  ctaText: string;
  colorTheme: PromotionTheme;
  openInNewTab?: boolean;
  promoCode?: string;
  impressions?: number;
  clicks?: number;
  updatedAt?: number;
}
